[package]
name = "repose"
version = "0.1.0"
authors = ["Lander Brandt"]

[dependencies]
irc = "0.13"
rocket = "0.3"
rocket_codegen = "0.3"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["tera_templates"]